---
volumes:
  mariadb-data: {}
  ojs-cache: {}
  ojs-files: {}
  ojs-public: {}

secrets:
  DB_ROOT_PASSWORD:
    file: ./secrets/DB_ROOT_PASSWORD
  OJS_DB_PASSWORD:
    file: ./secrets/OJS_DB_PASSWORD
  OJS_API_KEY_SECRET:
    file: ./secrets/OJS_API_KEY_SECRET
  OJS_SALT:
    file: ./secrets/OJS_SALT
  OJS_ADMIN_PASSWORD:
    file: ./secrets/OJS_ADMIN_PASSWORD
  OJS_SECRET_KEY:
    file: ./secrets/OJS_SECRET_KEY

services:
  init:
    image: islandora/base:6.0.1@sha256:34c281449a339dbce75f784da7dca237a3325022868d89ab5cf6d6d8e0ca24a1
    restart: no
    volumes:
      - ./secrets:/secrets:rw
      - ./scripts:/scripts:ro
      - ./docker-compose.yaml:/docker-compose.yaml:ro
    command: /scripts/generate-secrets.sh
  ojs:
    image: ghcr.io/libops/ojs:main
    build: .
    ports:
      - 80:80
    environment:
      OJS_OAI_REPOSITORY_ID: ojs.localhost
      OJS_ENABLE_BEACON: 1
    secrets:
      - source: DB_ROOT_PASSWORD
      - source: OJS_API_KEY_SECRET
      - source: OJS_SECRET_KEY
      - source: OJS_DB_PASSWORD
        target: DB_PASSWORD
      - source: OJS_SALT
      - source: OJS_ADMIN_PASSWORD
    volumes:
      - ojs-cache:/var/www/ojs/cache:rw
      - ojs-files:/var/www/files:rw
      - ojs-public:/var/www/ojs/public:rw
    depends_on:
      init:
        condition: service_completed_successfully
      mariadb:
        condition: service_started
  mariadb:
    image: islandora/mariadb:6.0.1@sha256:335df4225634f14095b337847e541d65b5abfa2fe051c7e2b93fae447cac1e58
    volumes:
      - mariadb-data:/var/lib/mysql:rw
    secrets:
      - source: DB_ROOT_PASSWORD
    depends_on:
      init:
        condition: service_completed_successfully
