---
volumes:
  mariadb-data: {}
  ojs-cache: {}
  ojs-files: {}
  ojs-public: {}

secrets:
  DB_ROOT_PASSWORD:
    file: ./secrets/DB_ROOT_PASSWORD
  OJS_DB_PASSWORD:
    file: ./secrets/OJS_DB_PASSWORD
  OJS_API_KEY_SECRET:
    file: ./secrets/OJS_API_KEY_SECRET
  OJS_SALT:
    file: ./secrets/OJS_SALT
  OJS_ADMIN_PASSWORD:
    file: ./secrets/OJS_ADMIN_PASSWORD
  OJS_SECRET_KEY:
    file: ./secrets/OJS_SECRET_KEY

services:
  init:
    image: islandora/base:6.0.10@sha256:00f16e56a20950f7b85e690b03c1e6e167625236bc77c56f4cd121dafd9ef578
    restart: no
    volumes:
      - ./secrets:/secrets:rw
      - ./scripts:/scripts:ro
      - ./docker-compose.yaml:/docker-compose.yaml:ro
    command: /scripts/generate-secrets.sh
    profiles: [none]
  ojs:
    image: ghcr.io/libops/ojs:main
    build: .
    ports:
      - 80:80
    environment:
      OJS_OAI_REPOSITORY_ID: ${DOMAIN:-localhost}
      OJS_ENABLE_BEACON: 1
      OJS_SMTP_SERVER: ${OJS_SMTP_SERVER:-}
    secrets:
      - source: DB_ROOT_PASSWORD
      - source: OJS_API_KEY_SECRET
      - source: OJS_SECRET_KEY
      - source: OJS_DB_PASSWORD
        target: DB_PASSWORD
      - source: OJS_SALT
      - source: OJS_ADMIN_PASSWORD
    volumes:
      - ojs-cache:/var/www/ojs/cache:rw
      - ojs-files:/var/www/files:rw
      - ojs-public:/var/www/ojs/public:rw
    depends_on:
      mariadb:
        condition: service_started
  mariadb:
    image: islandora/mariadb:6.0.10@sha256:a89a1152abe0fc3d5de66d071b4391dd8f18e5f4883bfa32a82caf45a46d96da
    volumes:
      - mariadb-data:/var/lib/mysql:rw
    secrets:
      - source: DB_ROOT_PASSWORD
