---
volumes:
  mariadb-data: {}
  ojs-cache: {}
  ojs-files: {}
  ojs-public: {}

secrets:
  DB_ROOT_PASSWORD:
    file: ./secrets/DB_ROOT_PASSWORD
  OJS_DB_PASSWORD:
    file: ./secrets/OJS_DB_PASSWORD
  OJS_API_KEY_SECRET:
    file: ./secrets/OJS_API_KEY_SECRET
  OJS_SALT:
    file: ./secrets/OJS_SALT
  OJS_ADMIN_PASSWORD:
    file: ./secrets/OJS_ADMIN_PASSWORD
  OJS_SECRET_KEY:
    file: ./secrets/OJS_SECRET_KEY

services:
  init:
    image: islandora/base:6.0.4@sha256:71a42ef7d1676e50a5860ac44fdde705fd0b38af0a7006c9d3371b8d88d0e311
    restart: no
    volumes:
      - ./secrets:/secrets:rw
      - ./scripts:/scripts:ro
      - ./docker-compose.yaml:/docker-compose.yaml:ro
    command: /scripts/generate-secrets.sh
    profiles: [none]
  ojs:
    image: ghcr.io/libops/ojs:main
    build: .
    ports:
      - 80:80
    environment:
      OJS_OAI_REPOSITORY_ID: ojs.localhost
      OJS_ENABLE_BEACON: 1
    secrets:
      - source: DB_ROOT_PASSWORD
      - source: OJS_API_KEY_SECRET
      - source: OJS_SECRET_KEY
      - source: OJS_DB_PASSWORD
        target: DB_PASSWORD
      - source: OJS_SALT
      - source: OJS_ADMIN_PASSWORD
    volumes:
      - ojs-cache:/var/www/ojs/cache:rw
      - ojs-files:/var/www/files:rw
      - ojs-public:/var/www/ojs/public:rw
    depends_on:
      mariadb:
        condition: service_started
  mariadb:
    image: islandora/mariadb:6.0.4@sha256:0394daa3f0d99d8dde5c273da4f55b340b76fc729dfdc8b8466155ecc486235a
    volumes:
      - mariadb-data:/var/lib/mysql:rw
    secrets:
      - source: DB_ROOT_PASSWORD
