---
networks:
  default:
volumes:
  mariadb-data: {}
  ojs-cache: {}
  ojs-files: {}
  ojs-public: {}

secrets:
  DB_ROOT_PASSWORD:
    file: ./secrets/DB_ROOT_PASSWORD
  OJS_DB_PASSWORD:
    file: ./secrets/OJS_DB_PASSWORD
  OJS_API_KEY_SECRET:
    file: ./secrets/OJS_API_KEY_SECRET
  OJS_SALT:
    file: ./secrets/OJS_SALT
  OJS_ADMIN_PASSWORD:
    file: ./secrets/OJS_ADMIN_PASSWORD
  OJS_SECRET_KEY:
    file: ./secrets/OJS_SECRET_KEY

services:
  init:
    image: islandora/base:6.4.3@sha256:67331b4a0a3adf90216ee7e192013842790ddda61124ccdced18a35b7e8aace9
    restart: no
    volumes:
      - ./secrets:/secrets:rw
      - ./scripts:/scripts:ro
      - ./docker-compose.yaml:/docker-compose.yaml:ro
    command: /scripts/generate-secrets.sh
    profiles: [none]
  ojs:
    image: ghcr.io/libops/ojs:main
    build: .
    networks:
      - default
    ports:
      - 80:80
    environment:
      OJS_OAI_REPOSITORY_ID: ${DOMAIN:-localhost}
      OJS_ENABLE_BEACON: 1
      OJS_SMTP_SERVER: ${OJS_SMTP_SERVER:-}
      OJS_ENABLE_HTTPS: "true"
      OJS_BASE_URL: "https://${DOMAIN:-localhost}"
    secrets:
      - source: DB_ROOT_PASSWORD
      - source: OJS_API_KEY_SECRET
      - source: OJS_SECRET_KEY
      - source: OJS_DB_PASSWORD
        target: DB_PASSWORD
      - source: OJS_SALT
      - source: OJS_ADMIN_PASSWORD
    volumes:
      - ojs-cache:/var/www/ojs/cache:rw
      - ojs-files:/var/www/files:rw
      - ojs-public:/var/www/ojs/public:rw
    depends_on:
      mariadb:
        condition: service_started
  mariadb:
    image: islandora/mariadb:6.4.3@sha256:8f41414cba3286567e0590fa5428e2860e3351f13b1377666b1d362b01e6fe6e
    networks:
      - default
    volumes:
      - mariadb-data:/var/lib/mysql:rw
    secrets:
      - source: DB_ROOT_PASSWORD
