#!/command/with-contenv bash

DIRS=(
  /var/www/files
  /var/www/ojs/cache
  /var/www/ojs/public
)
echo "Setting OJS permissions..."
for DIR in "${DIRS[@]}"; do
  echo "Setting permissions on $DIR"
  chown -R nginx:nginx "$DIR"
  find "$DIR" -type d -exec chmod 750 {} \;
  find "$DIR" -type f -exec chmod 640 {} \;
done
echo "OJS permissions set: dirs=750, files=640"
