name: lint-test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: lint-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: lint
        run: make lint

      - name: test
        run: make test
